#!/usr/bin/env bash
# sync-agent-registry — assemble ~/.agents/registry.toml from every peer's
# ~/.agents/local.toml, then push the assembled view back to peers.
# Mesh membership is configured in ~/.agents/peers.conf (one SSH alias per
# line). This host's alias comes from ~/.agents/self.conf, falling back to
# `hostname -s` if that file is absent.
set -euo pipefail

CFG="${HOME}/.agents/peers.conf"
LOCAL="${HOME}/.agents/local.toml"
ASSEMBLED="${HOME}/.agents/registry.toml"
mkdir -p "$(dirname "$ASSEMBLED")"

[ -r "$CFG" ] || { echo "missing $CFG — cannot determine mesh peers" >&2; exit 1; }
mapfile -t ALL < <(sed -e 's/#.*//' -e 's/[[:space:]]*$//' "$CFG" | grep -vE '^[[:space:]]*$')

if [ -r "${HOME}/.agents/self.conf" ]; then
  SELF=$(head -1 "${HOME}/.agents/self.conf" | sed 's/[[:space:]]//g')
else
  SELF="$(hostname -s)"
fi

PEERS=()
for p in "${ALL[@]}"; do
  [ "$p" = "$SELF" ] && continue
  PEERS+=( "$p" )
done

stage=$(mktemp -d)
trap 'rm -rf "$stage"' EXIT
cp -f "$LOCAL" "$stage/00-${SELF}.toml" 2>/dev/null || : > "$stage/00-${SELF}.toml"
for p in "${PEERS[@]}"; do
  rsync -aq --timeout=5 "$p:~/.agents/local.toml" "$stage/${p}.toml" 2>/dev/null || : > "$stage/${p}.toml"
done

{
  printf "# Agent registry - auto-assembled from each peer's ~/.agents/local.toml.\n"
  printf '# DO NOT edit this file directly. AI agents should advertise themselves with:\n'
  printf '#   agent-self-identify --role "..." --scope "..."\n'
  printf '# Mesh: %s\n' "${ALL[*]}"
  printf '# Last assembled: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  for f in "$stage"/*.toml; do
    [ -s "$f" ] || continue
    awk 'NF' "$f"
  done
} > "$ASSEMBLED"

for p in "${PEERS[@]}"; do
  rsync -aq --timeout=5 "$ASSEMBLED" "$p:~/.agents/registry.toml" 2>/dev/null || true
done

n=$(grep -c '^\[agents\.' "$ASSEMBLED" || true)
echo "$(date -u +%H:%M:%SZ) sync-agent-registry: assembled $n agents from {${SELF}, ${PEERS[*]}}"
